### ISSUE TITLE
Class Notes

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#20]
# Form Migration

## Old Form Information

- **Form URL:** https://alumni.mercer.edu/classnotes/
- **Handler URL:** https://apps.mercer.edu/forms/alumni_classnotes.cfm
- **To:** records@mercer.edu
- **From:** ""#Form.first_name# #Form.last_name#"" <#Form.email#>
- **Subject:** [Class Notes] New note
- **Redirect:** http://alumni.mercer.edu/classnotes/thanks/

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="false">
<!-- Required -->
<input type="hidden" name="*to" value="records@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="Alumni - Class Notes">
<input type="hidden" name="*redirect" value="http://alumni.mercer.edu/classnotes/thanks/">
<input type="hidden" name="*subject" value="[Class Notes] New note">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [x] Update form action attribute
- [x] Add hidden fields
- [x] Verify action and hidden field values are correct
- [x] Test

**Comment by Sporkyy** [comment]
I'm not reproducing putting form values into the "From" field of the email because that's a [DMARC](https://dmarc.org/) violation.

**Comment by Sporkyy** [comment]
Also, there's some parts additional spam prevention lurking in the code. I didn't do anything to try to fix it or re-implement a working version.
