### ISSUE TITLE
Look Up Class Listservs

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#24]
# Form Migration

## Old Form Information

- **Form URL:** https://it.mercer.edu/faculty/email/email_listservs.htm
- **Handler URL:** https://apps.mercer.edu/forms/it-class-listservs-signup.cfm
- **To:** mailserv@mercer.edu
- **From:** _from form_
- **Subject:** blank
- **Redirect:** http://it.mercer.edu/faculty/email/email_listservs-thanks.htm

## New Form Information

See: https://github.com/merceruniversity/easy-listservs

**Comment by Sporkyy** [comment]
This works differently from most forms.

The information entered into the form isn't read by humans, it's for use by another program.

**Comment by Sporkyy** [comment]
Updated the shared include file at `\\bazooka\c$\inetpubit\wwwroot\include\email\listservs-special_interest.htm`

**Comment by Sporkyy** [comment]
This is done.
