### ISSUE TITLE
Outage Notice

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#25]
# Form Migration

## Old Form Information

- **Form URL:** https://it.mercer.edu/faculty/outage_notice.htm
- **Handler URL:** https://apps.mercer.edu/forms/it-service-request-form.cfm
- **To:** hmc@mercer.edu
- **From:** _from form_
- **Subject:** IT Service Request
- **Redirect:** http://it.mercer.edu/Faculty/notification_form_confirm.htm

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="">
<!-- Required -->
<input type="hidden" name="*to" value="hmc@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="IT - Service Request">
<input type="hidden" name="*redirect" value="http://it.mercer.edu/Faculty/notification_form_confirm.htm">
<input type="hidden" name="*subject" value="IT Service Request">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [x] Update form action attribute
- [x] Add hidden fields
- [x] Verify action and hidden field values are correct
- [x] Test

**Comment by Sporkyy** [comment]
This is doing a bit more than other forms.

**Comment by Sporkyy** [comment]
Or maybe it's not. There's code for handling uploads, but the place where they're being stored doesn't exist. And it's in the web root and that's asking for trouble since it's a public form.

**Comment by Sporkyy** [comment]
The upload functionality isn't going to work anymore, but it doesn't look like it ever worked or was ever used.
