### ISSUE TITLE
Special Interest Listservs

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#26]
## Old Form Information

- http://it.mercer.edu/faculty/email/email_listservs-special_interest_listservs.htm 
- http://it.mercer.edu/student/email/email_listservs-special_interest_listservs.htm

https://apps.mercer.edu/forms/subscribe2list.cfm

## New Form Information

See: https://github.com/merceruniversity/easy-listservs

**Comment by Sporkyy** [comment]
These forms are DMARC violations waiting to happen.

**Comment by Sporkyy** [comment]
They can both be replaced with front-end code to generate pre-written subjects and bodies that open in the default mail client. That will require an email client, but these are email lists, so it's a safe assumption. That will solve the DMARC problem as well.

**Comment by cinakur** [comment]
so instead of a form, it'll be "Hello, please add me to this list"?

**Comment by Sporkyy** [comment]
It will be a form, but instead of submitting to a backend CFML page, it generates a `mailto:` link.

It will get a subject and body like here https://css-tricks.com/snippets/html/mailto-links/

It will also solve the [DMARC](https://dmarc.org/) issue that I keep harping about

**Comment by Sporkyy** [comment]
The same solution can solve #24 too.

**Comment by Sporkyy** [comment]
#24 and #26 should spin off another repo to hold "simplified" versions of the form before trying to integrate them into the IT site.

**Comment by Sporkyy** [comment]
https://github.com/InteractiveDesignAndDevelopment/easy-listservs

**Comment by Sporkyy** [comment]
Updated the shared include file at `\\bazooka\c$\inetpubit\wwwroot\include\email\listservs-special_interest.htm`
