### ISSUE TITLE
New Employee Account Request

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#27]
# Form Migration

## Old Form Information

- **Form URL:** https://it.mercer.edu/faculty/new_employees/request_form.htm
- **Handler URL:** https://apps.mercer.edu/forms/new_employee_request.cfm
- **To:** helpdesk@mercer.edu
- **From:** _from form_
- **Subject:** New Employee
- **Redirect:** http://it.mercer.edu/faculty/new_employees/request_form_thanks.htm

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="">
<!-- Required -->
<input type="hidden" name="*to" value="helpdesk@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="IT - New Employee">
<input type="hidden" name="*redirect" value="http://it.mercer.edu/faculty/new_employees/request_form_thanks.htm">
<input type="hidden" name="*subject" value="New Employee">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [x] Update form action attribute
- [x] Add hidden fields
- [x] Verify action and hidden field values are correct
- [x] Test

**Comment by Sporkyy** [comment]
Somewhat surprisingly, this one worked.
