### ISSUE TITLE
PharmD RSVP

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#31]
/forms/pharmacy_pharmdisrsvp.cfm | http://pharmacy.mercer.edu/admissions/pharmdisrsvp.cfm
-- | --

**Comment by Sporkyy** [comment]
How'd I forget this one?

**Comment by Sporkyy** [comment]
The [form on the Pharmacy site](https://pharmacy.mercer.edu/admissions/pharmdisrsvp.cfm) is a 404. I'm closing it.
