### ISSUE TITLE
Stetson B&E Application

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/hubbabubba-chewbacca-migration#35]
# Form Migration

## Old Form Information

- **Form URL:** https://forms.mercer.edu/admissions/secureforms/atlssbeapply.shtm
- **Handler URL:** https://apps.mercer.edu/forms/atlssbeapply.cfm
- **To:** atlbusadm@mercer.edu
- **From:** _from form_
- **Subject:** Application for Admission to SSBE...
- **Redirect:** https://business.mercer.edu/application-thank-you.cfm

## New Form information

```html
<form ... action="https://formhandlers.mercer.edu/" ... >
```

Remove unused fields below.

(But nothing will break if it's blank.)

```html
<!-- Testing -->
<input type="hidden" name="*debug" value="">
<!-- Required -->
<input type="hidden" name="*to" value="atlbusadm@mercer.edu">
<!-- Recommended -->
<input type="hidden" name="*formname" value="SSBE - Application for Admission">
<input type="hidden" name="*redirect" value="https://business.mercer.edu/application-thank-you.cfm">
<input type="hidden" name="*subject" value="Application for Admission to SSBE...">
<!-- Situational -->
<input type="hidden" name="*bcc" value="">
<input type="hidden" name="*cc" value="">
<input type="hidden" name="*honeypot" value="">
<input type="hidden" name="*replyto" value="">
```

## Tasks

- [x] Update form action attribute
- [x] Add hidden fields
- [x] Verify action and hidden field values are correct
- [x] Test

**Comment by Sporkyy** [comment]
The text from the confirmation email was moved into this confirmation page: https://business.mercer.edu/application-thank-you.cfm

Confirmation emails sent to the filler-out of a form isn't something supported currently in the new system.
