### ISSUE TITLE
Make Elizabeth Cry

### ISSUE THREAD

**Issue by osmusja** [merceruniversity/hubbabubba-chewbacca-migration#38]
<3

**Comment by osmusja** [comment]
@elcopeland

**Comment by cinakur** [comment]
that's not very nice

**Comment by cinakur** [comment]
Why would you want to make me cry @osmusja

**Comment by cinakur** [comment]
I did my part here, assigning @Sporkyy to try.

**Comment by cinakur** [comment]
No, I'm assigning back to you @osmusja

**Comment by Sporkyy** [comment]
**MISSION ACCOMPLISHED**

**Comment by osmusja** [comment]
@elcopeland SO. MUCH.

**Comment by cinakur** [comment]
@osmusja I feel the love. It's a-ok. 

fwiw, this was the kicker: 

> _nobody cares_
> _nobody understands_
> _nobody cares they don't understand_
> _you are the problem_

Hurts cuz it's true loooool
