### ISSUE TITLE
Create redirects for al the directories under apps.mercer.edu

### ISSUE THREAD

**Issue by Sporkyy** [merceruniversity/hubbabubba-chewbacca-migration#44]
List all directories and redirect targets here.

| Directory | Redirect |
|--|--|
|directory | https://directory.mercer.edu |

**Comment by cinakur** [comment]
[For reference](https://drive.google.com/open?id=1p9lLrxp0IEdul0NkgJKpQwZGyJF4HKfs)

**Comment by Sporkyy** [comment]
Done in #42
